import twirl

twirl.manifest(
    twirl.Table(
        schema=twirl.Schema(
            [
                twirl.Column("_airbyte_unique_key", twirl.String()),
                twirl.Column("issue_url", twirl.String()),
                twirl.Column("_links", twirl.String()),
                twirl.Column("diff_url", twirl.String()),
                twirl.Column("assignees", twirl.Array(value_type=twirl.String())),
                twirl.Column("created_at", twirl.Timestamp(unit="us", tz="UTC")),
                twirl.Column("requested_reviewers", twirl.Array(value_type=twirl.String())),
                twirl.Column("body", twirl.String()),
                twirl.Column("title", twirl.String()),
                twirl.Column("repository", twirl.String()),
                twirl.Column("requested_teams", twirl.Array(value_type=twirl.String())),
                twirl.Column("head", twirl.String()),
                twirl.Column("author_association", twirl.String()),
                twirl.Column("number", twirl.Integer()),
                twirl.Column("patch_url", twirl.String()),
                twirl.Column("updated_at", twirl.Timestamp(unit="us", tz="UTC"), is_event_time=True),
                twirl.Column("draft", twirl.Bool()),
                twirl.Column("comments_url", twirl.String()),
                twirl.Column("merge_commit_sha", twirl.String()),
                twirl.Column("review_comment_url", twirl.String()),
                twirl.Column("active_lock_reason", twirl.String()),
                twirl.Column("id", twirl.Integer()),
                twirl.Column("state", twirl.String()),
                twirl.Column("locked", twirl.Bool()),
                twirl.Column("commits_url", twirl.String()),
                twirl.Column("closed_at", twirl.Timestamp(unit="us", tz="UTC")),
                twirl.Column("statuses_url", twirl.String()),
                twirl.Column("merged_at", twirl.Timestamp(unit="us", tz="UTC")),
                twirl.Column("auto_merge", twirl.String()),
                twirl.Column("url", twirl.String()),
                twirl.Column("labels", twirl.Array(value_type=twirl.String())),
                twirl.Column("milestone", twirl.String()),
                twirl.Column("html_url", twirl.String()),
                twirl.Column("review_comments_url", twirl.String()),
                twirl.Column("assignee", twirl.String()),
                twirl.Column("user", twirl.String()),
                twirl.Column("base", twirl.String()),
                twirl.Column("node_id", twirl.String()),
                twirl.Column("_airbyte_ab_id", twirl.String()),
                twirl.Column("_airbyte_emitted_at", twirl.Timestamp(unit="us", tz="UTC")),
                twirl.Column("_airbyte_normalized_at", twirl.Timestamp(unit="us", tz="UTC")),
                twirl.Column("_airbyte_pull_requests_hashid", twirl.String()),
            ]
        ),
        job=twirl.External(),
        trigger_conditions=twirl.TriggerAt(cron_string="37 * * * *"),
        tags=["engineering", "github_predictions"],
    )
)
